### ISSUE TITLE
semantics: Support properties that detect all command handles

### ISSUE THREAD

**Issue by mfeliu** [plexil-rwl-support/PLEXIL5#21]
As reported by @mikedalal:

'We would like to check properties that are based on any of the PLEXIL command handles.  These handles are all supported by `psx2maude`, but the checker seems to only provide one related predicate `commandIsExecuting` which I think (but am not sure) means that the command node is executing.

For example, we'd like to express properties that ask whether a command succeeded, failed, etc.'

I propose a pair of properties:
- `hasCmdHandle?(id,handle)` checks the`handle` of the fully qualified id command 
- `hasNoCmdHandle?(id)` checks that the fully qualified id command has not received a handle yet

**Comment by mikedalal** [comment]
I wanted to check something about the behavior of the production executive with respect to commands before replying.  And yes, this pair of properties seems exactly what's needed.  I'll test your PR soon.
