### ISSUE TITLE
semantics: Bug: counterexample inputs accumulate

### ISSUE THREAD

**Issue by mikedalal** [plexil-rwl-support/PLEXIL5#47]
When the model checker produces a counterexample, at least for a deterministic environment, the output has each entry appending the previous entry.  An example counterexample and the input environment used is attached.  Assumption: the counterexample for a grounded script is always the script itself.

[counterexample.tar.gz](https://github.com/plexil-rwl-support/PLEXIL5/files/11726062/counterexample.tar.gz)

**Comment by mfeliu** [comment]
@mikedalal , can you share the plan that gets the counterexample?
