### ISSUE TITLE
command1.ple regression test fails

### ISSUE THREAD

**Issue by mfeliu** [plexil-rwl-support/PLEXIL5#5]
It looks like a parsing problem

**Comment by Koliopkl** [comment]
Where it says `(CommandName)("")`, are we supposed to resolve the value of the variable `CommandName` to be left with a call for a command `foo("")` ?

**Comment by mfeliu** [comment]
No, it look at the .ple file you will notice that name is a string variable name whose value is the name of the command, so we have to consider command identifiers as strings, and we have to evaluate the value provided as the identifier to get a string from it. But don't think about this issue right now. I plan to tackle it. @Koliopkl  @ajjimenezm you should review examples that are not passing, evaluate how difficult do you think it is, and create an issue for each of those examples. And then you work on them on that issue and we discuss the changes needed, etc. We can talk more about it tomorrow.
